name: Build
on:
  # cant have workflow dispatch
  push:
    tags:
      - 'v*'
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
      - name: Download perk images
        run: cd extra && npm i && node getPerks.js
      - uses: abel0b/setup-premake@v2.1
        with:
          version: "5.0.0-beta2"
      - uses: actions/cache@v3
        id: cache
        with:
          path: opencv
          key: opencv460
      - name: Download opencv
        if: steps.cache.outputs.cache-hit != 'true'
        shell: powershell
        run: Invoke-WebRequest -Uri https://github.com/opencv/opencv/releases/download/4.6.0/opencv-4.6.0-vc14_vc15.exe -OutFile opencv.exe
      - name: Extract opencv
        if: steps.cache.outputs.cache-hit != 'true'
        shell: cmd
        run: start /b /wait opencv.exe -o"." -y
      - name: Setup build
        shell: cmd
        run: premake5 --opencv="opencv" vs2019
      - name: Build Binary
        shell: cmd
        run: "\"%programfiles(x86)%\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\msbuild.exe\""
      - name: Create artifact
        uses: actions/upload-artifact@v3
        with:
          name: FogBuddy
          path: '.\\bin\\Release\\FogBuddy'
      - name: Create Release Archive
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'FogBuddy.zip'
          path: '.\\bin\\Release\\FogBuddy'
      - name: Create Release
        uses: ncipollo/release-action@v1.11.0
        with:
          artifactErrorsFailBuild: true
          artifacts: 'FogBuddy.zip'
          body: Automated Release by GitHub Action CI. Before you download, make sure you've familiarised yourself with the [risks](https://github.com/MrTipson/FogBuddy#risks) and [personal responsibility](https://github.com/MrTipson/FogBuddy#personal-responsibility) sections.
          generateReleaseNotes: true